### ISSUE TITLE
Clone repo failed

### ISSUE THREAD

**Issue by hungtrieu07** [A-Coom/coomer.party-scraper#4]
```
Submodule 'scraping_utils' (https://github.com/A-Coom/coomer.party-scraper/scraping_utils) registered for path 'scraping_utils'
Cloning into 'D:/segg/tools/coomer.party-scraper/scraping_utils'...
remote: Not Found
fatal: repository 'https://github.com/A-Coom/coomer.party-scraper/scraping_utils/' not found
fatal: clone of 'https://github.com/A-Coom/coomer.party-scraper/scraping_utils' into submodule path 'D:/segg/tools/coomer.party-scraper/scraping_utils' failed
Failed to clone 'scraping_utils'. Retry scheduled
Cloning into 'D:/segg/tools/coomer.party-scraper/scraping_utils'...
remote: Not Found
fatal: repository 'https://github.com/A-Coom/coomer.party-scraper/scraping_utils/' not found
fatal: clone of 'https://github.com/A-Coom/coomer.party-scraper/scraping_utils' into submodule path 'D:/segg/tools/coomer.party-scraper/scraping_utils' failed
Failed to clone 'scraping_utils' a second time, aborting
```

When i run .exe file, it return this error:

```
Traceback (most recent call last):
  File "scrape.py", line 135, in <module>
  File "scrape.py", line 110, in main
  File "scrape.py", line 36, in download_media
  File "scraping_utils\scraping_utils.py", line 220, in multithread_download_urls
UnboundLocalError: local variable 'download_threads' referenced before assignment
[16892] Failed to execute script 'scrape' due to unhandled exception!
```

**Comment by A-Coom** [comment]
Thanks for opening an issue.

It appears that further error checking is required to confirm that downloadable content is found before attempting to download. 

Can you please describe how you are running the .exe file? (i.e. are you double clicking it or running it in the terminal?)
    - If you are double clicking it, what is the input you provide?
    - If you are running it in the terminal, what is the full command?

**Comment by hungtrieu07** [comment]
> Thanks for opening an issue.
> 
> It appears that further error checking is required to confirm that downloadable content is found before attempting to download.
> 
> Can you please describe how you are running the .exe file? (i.e. are you double clicking it or running it in the terminal?) - If you are double clicking it, what is the input you provide? - If you are running it in the terminal, what is the full command?

Thanks for reply. The error will be described below:

If I double click on the .exe file, enter the link and folder location, include video, and press Enter, I can see it fetching the post, but after that the command line disapeared. So that I choose the way, open a terminal (Command Prompt) in the folder stored .exe file, run it in terminal, do exactly when double click the .exe file, the traceback above appeared. I try with another link and it works, maybe the link I try to download have some problem. Can you try that, i will post the link below:
https://www.coomer.su/onlyfans/user/umekoj0910

**Comment by A-Coom** [comment]
Thank you for the details.

The last page was not being included in the download queue, which becomes obvious when there is only one page. I corrected this so that all pages are included and the link you provided will now work.

Please redownload release 2.0 and let me know if the problem is solved on your side.

**Comment by hungtrieu07** [comment]
Thanks for your efforts, the tool work perfectly. I will closed this issue.
