### ISSUE TITLE
Media Download optimization 

### ISSUE THREAD

**Issue by emptyLIMBOempty** [A-Coom/coomer.party-scraper#8]
Can you please add an option to choose only the **videos** after pasting the landing page for the artist?
Thanks again for this amazing tool 🔥

**Comment by A-Coom** [comment]
This will be included in the next release along with better naming for the downloaded files. Hopefully in the next week or so. Thanks!

**Comment by A-Coom** [comment]
Included in commit [d0c19cf](https://github.com/A-Coom/coomer.party-scraper/commit/d0c19cfa890c868e7dfce2eda8129acc503ea649).Try it out via platform agnostic execution. If no errors, I'll update the release

**Comment by A-Coom** [comment]
Personal testing has shown no new bugs.
